### ISSUE TITLE
Interesting project, thanks!

### ISSUE THREAD

**Issue by Jiaqi-Chen-00** [kulits/IG-LLM#1]
Looking forward to open source, when do you plan to make the code available?

**Comment by xiwen1** [comment]
There seems no available pre-trained checkpoints right now. Do you plan to release some checkpoints? It would be really helpful.

**Comment by kulits** [comment]
@Jiaqi-Chen-00 Thank you for closing the issue. I apologize for not updating it following the code release.

@xiwen1 I can package the checkpoints up if there is interest in them. Which in particular are you looking for?
